<?php

/**
 * @file
 * Contains bigpipetest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bigpipetest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bigpipetest module.
    case 'help.page.bigpipetest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bigpipetest_theme() {
  return [
    'bigpipetest' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function bigpipetest_cron() {
  // Invalidate Weather cache tag when the cron is executed.
  \Drupal\Core\Cache\Cache::invalidateTags(['weather_forecast_block']);
}