<?php

/**
 * @file
 * Contains opendatasoft.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opendatasoft_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opendatasoft module.
    case 'help.page.opendatasoft':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage requests to the OpenDataSoft API') . '</p>';
      return $output;

    default:
  }
}
